T2_DelCastillo_JoseMiguel/Models/Distribuidor.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Contracts;


namespace T2_DelCastillo_JoseMiguel.Models
{
    public class Distribuidor
    {
        [Key]

        [Required(ErrorMessage = "El ID es obligatorio.")]
        public int id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        public string nombreDistribuidor { get; set; }

        [Required(ErrorMessage = "La razon social es obligatoria.")]
        public string razonSocial { get; set; }

        [Required(ErrorMessage = "El telefono es obligatorio.")]
        public int telefono { get; set; }

        [Required(ErrorMessage = "El año es obligatorio.")]
        [Range(1900, 3000, ErrorMessage = "El año es entre 1900 y 3000")]
        public int anioInicioOperacion { get; set; }

        [Required(ErrorMessage = "El contacto es obligatorio.")]
        public string contacto { get; set; }
        


    }
}

T2_DelCastillo_JoseMiguel/Models/ErrorViewModel.cs
namespace T2_DelCastillo_JoseMiguel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

T2_DelCastillo_JoseMiguel/Controllers/DistribuidorController.cs
using Microsoft.AspNetCore.Mvc;
using T2_DelCastillo_JoseMiguel.Models;
using T2_DelCastillo_JoseMiguel.Datos;

namespace T2_DelCastillo_JoseMiguel.Controllers
{
    public class DistribuidorController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DistribuidorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Distribuidor> lista = _db.Distribuidor;
            return View(lista);
        }

        public IActionResult Crear()
        {
            return View();  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Add(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);
            
        }
            
        //Get Editar
        public IActionResult Editar(int? Id)
        {
            if (Id==null || Id==0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Distribuidor distribuidor)
        {
            if (ModelState.IsValid)
            {
                _db.Distribuidor.Update(distribuidor);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(distribuidor);
        }

        //Get Eliminar
        public IActionResult Eliminar(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var obj = _db.Distribuidor.Find(Id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //Post Eliminar
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Eliminar(Distribuidor distribuidor)
        {
            if (distribuidor == null)
            {
                return NotFound();
            }
            _db.Distribuidor.Remove(distribuidor);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

T2_DelCastillo_JoseMiguel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using T2_DelCastillo_JoseMiguel.Models;

namespace T2_DelCastillo_JoseMiguel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Walmart()
        {
            return View();
        }
        public IActionResult Amazon()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

T2_DelCastillo_JoseMiguel/Views/Distribuidor/Crear.cshtml
@model T2_DelCastillo_JoseMiguel.Models.Distribuidor
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear</h1>

<form method="post" asp-action="Crear">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Nuevo Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="id" class="form-label">ID Distribuidor</label>
                    <input asp-for="id" class="form-control"/>
                    <span asp-validation-for="id" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="nombreDistribuidor" class="form-label">Nombre</label>
                    <input asp-for="nombreDistribuidor" class="form-control" />
                    <span asp-validation-for="nombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="razonSocial" class="form-label">Razón Social</label>
                    <input asp-for="razonSocial" class="form-control" />
                    <span asp-validation-for="razonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="telefono" class="form-label">Teléfono</label>
                    <input asp-for="telefono" class="form-control" />
                    <span asp-validation-for="telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="anioInicioOperacion" class="form-label">Año de Inicio</label>
                    <input asp-for="anioInicioOperacion" class="form-control" />
                    <span asp-validation-for="anioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="contacto" class="form-label">Contacto</label>
                    <input asp-for="contacto" class="form-control" />
                    <span asp-validation-for="contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Crear Nueva</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>

    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

T2_DelCastillo_JoseMiguel/Views/Distribuidor/Editar.cshtml
@model T2_DelCastillo_JoseMiguel.Models.Distribuidor
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<form method="post" asp-action="Editar">
    <input asp-for="id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Editar Distribuidor</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="id" class="form-label">ID Distribuidor</label>
                    <input asp-for="id" class="form-control" />
                    <span asp-validation-for="id" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="nombreDistribuidor" class="form-label">Nombre</label>
                    <input asp-for="nombreDistribuidor" class="form-control" />
                    <span asp-validation-for="nombreDistribuidor" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="razonSocial" class="form-label">Razón Social</label>
                    <input asp-for="razonSocial" class="form-control" />
                    <span asp-validation-for="razonSocial" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="telefono" class="form-label">Teléfono</label>
                    <input asp-for="telefono" class="form-control" />
                    <span asp-validation-for="telefono" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="anioInicioOperacion" class="form-label">Año de Inicio</label>
                    <input asp-for="anioInicioOperacion" class="form-control" />
                    <span asp-validation-for="anioInicioOperacion" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="contacto" class="form-label">Contacto</label>
                    <input asp-for="contacto" class="form-control" />
                    <span asp-validation-for="contacto" class="text-danger"></span>
                </div>
            </div>

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Actualizar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>

    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_DelCastillo_JoseMiguel/Views/Distribuidor/Eliminar.cshtml
@model T2_DelCastillo_JoseMiguel.Models.Distribuidor
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>

<form method="post" asp-action="Eliminar">
    <input asp-for="id" hidden />
    <div class="border p-3">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">¿Está seguro de eliminar a este distribuidor?</h2>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="id" class="form-label">ID Distribuidor</label>
                    <input asp-for="id" disabled class="form-control" />
                    
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="nombreDistribuidor" class="form-label">Nombre</label>
                    <input asp-for="nombreDistribuidor" disabled class="form-control" />
                    
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="razonSocial" class="form-label">Razón Social</label>
                    <input asp-for="razonSocial" disabled class="form-control" />
                    
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="telefono" class="form-label">Teléfono</label>
                    <input asp-for="telefono" disabled class="form-control" />
                    
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="anioInicioOperacion" class="form-label">Año de Inicio</label>
                    <input asp-for="anioInicioOperacion" disabled class="form-control" />
                    
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <label asp-for="contacto" class="form-label">Contacto</label>
                    <input asp-for="contacto" disabled class="form-control" />
                    
                </div>
            </div>

            <br />

            <div class="d-grid gap-2 d-md-block">
                <button type="submit" class="btn btn-primary">Eliminar</button>
                <a asp-controller="Distribuidor" asp-action="Index" class="btn btn-success">Regresar</a>
            </div>

        </div>

    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

T2_DelCastillo_JoseMiguel/Views/Distribuidor/Index.cshtml
@model IEnumerable<T2_DelCastillo_JoseMiguel.Models.Distribuidor>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container pt-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Lista de Distribuidores</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Distribuidor" asp-action="Crear" class="btn btn-primary">Nuevo Distribuidor</a>
        </div>
    </div>

    <br/>

    @if (Model.Count() >0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Nombre Distribuidor</th>
                    <th>Razon Social</th>
                    <th>Telefono</th>
                    <th>Año de Inicio</th>
                    <th>Contacto</th>
                </tr>
                
            </thead>

            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <th width="10%">@item.id</th>
                        <th width="20%">@item.nombreDistribuidor</th>
                        <th width="15%">@item.razonSocial</th>
                        <th width="15%">@item.telefono</th>
                        <th width="15%">@item.anioInicioOperacion</th>
                        <th width="15%">@item.contacto</th>
                        <th>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Distribuidor" asp-action="Editar" asp-route-Id="@item.id" class="btn btn-primary mx-2">Editar</a>
                                <a asp-controller="Distribuidor" asp-action="Eliminar" asp-route-Id="@item.id" class="btn btn-danger mx-2">Eliminar</a>
                            </div>
                        </th>
                    </tr>

                }
            </tbody>
        </table>
    }
    else
    {
        <p>No hay registros de Categoría</p>
    }

</div>

T2_DelCastillo_JoseMiguel/Views/Home/Amazon.cshtml
@{
    ViewData["Title"] = "Amazon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<title>Amazon</title>
<br />
<div>
    <div class="container">
        <h1 style="text-align: center; text-decoration: underline;" ">Distribuidor Amazon Inc.</h1>
        <br />
        <img src="https://i0.wp.com/blogs.unsw.edu.au/nowideas/files/2018/03/amazon.jpg?fit=840%2C440&ssl=1" alt="Amazon" width="600" height="auto" style="display: block; margin: 0 auto;">
        <div class="description">
            <br />
            <p><strong>Walmart Inc.:</strong> Amazon es uno de los mayores distribuidores en línea del mundo. Fundada por Jeff Bezos en 1994, la compañía comenzó como una librería en línea, pero rápidamente se expandió para vender una amplia variedad de productos y servicios, incluidos dispositivos electrónicos, ropa, muebles, alimentos, juguetes y joyería. Amazon es conocida por su rápida y eficiente red de distribución y su innovación en logística y tecnología.</p>
        </div>
    </div>
</div>

T2_DelCastillo_JoseMiguel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

T2_DelCastillo_JoseMiguel/Views/Home/Walmart.cshtml
@model T2_DelCastillo_JoseMiguel.Models.Distribuidor

@{
    ViewData["Title"] = "Walmart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<title>Walmart</title>
<br />
<div>
    <div class="container">
        <h1 style="text-align: center; text-decoration: underline;" ">Distribuidora Walmart Inc.</h1>
        <br />
        <img src="https://tentulogo.com/wp-content/uploads/2017/10/walmart-logo.jpg" alt="Walmart" width="600" height="auto" style="display: block; margin: 0 auto;">
        <div class="description">
            <br />
            <p><strong>Walmart Inc.:</strong> Es una de las mayores cadenas de tiendas minoristas del mundo, con una vasta red de tiendas físicas y una presencia significativa en el comercio electrónico. Walmart opera en numerosos países y es conocido por su capacidad de distribución eficiente y su cadena de suministro global.</p>
        </div>
    </div>
</div>

T2_DelCastillo_JoseMiguel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T2_DelCastillo_JoseMiguel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T2_DelCastillo_JoseMiguel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T2_DelCastillo_JoseMiguel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Distribuidor" asp-action="Index">Distribuidor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Walmart">Walmart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Amazon">Amazon</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - T2_DelCastillo_JoseMiguel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>